---
- name: Install and Configure Zabbix Agent
  hosts: all
  become: true
  tasks:

    - name: Update apt repositories
      apt:
        update_cache: yes

    - name: Install Zabbix Agent
      apt:
        name: zabbix-agent
        state: present

    - name: Configure Zabbix Agent to connect to the Zabbix Server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: 'Server=3.111.67.207'

    - name: Configure Zabbix Agent active mode
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: 'ServerActive=3.111.67.207:81'

    - name: Start and enable Zabbix Agent service
      systemd:
        name: zabbix-agent
        state: started
        enabled: true

    - name: Check Zabbix Agent status
      systemd:
        name: zabbix-agent
        state: started
      register: zabbix_agent_status

    - name: Output Zabbix Agent status
      debug:
        msg: "Zabbix Agent is running: {{ zabbix_agent_status.status }}"
