---
- name: Install and Configure Zabbix Agent
  hosts: all
  become: yes
  vars_prompt:
    - name: "zabbix_server"
      prompt: "Enter the Zabbix server IP address"
      private: no
    - name: "zabbix_server_active"
      prompt: "Enter the Zabbix server active IP and port (format: IP:PORT)"
      private: no

  tasks:
    - name: Update apt repository and install zabbix-agent
      apt:
        update_cache: yes
        name: zabbix-agent
        state: present

    - name: Configure zabbix_agentd.conf with provided server details
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^Server='
        line: "Server={{ zabbix_server }}"

    - name: Configure zabbix_agentd.conf for active server
      lineinfile:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: '^ServerActive='
        line: "ServerActive={{ zabbix_server_active }}"

    - name: Start the Zabbix agent service
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes

    - name: Check the status of Zabbix agent service
      systemd:
        name: zabbix-agent
        state: started
        enabled: yes
        daemon_reload: yes
      register: zabbix_status

    - name: Display Zabbix agent status
      debug:
        var: zabbix_status

    - name: Restart Zabbix agent service to apply configuration changes
      systemd:
        name: zabbix-agent
        state: restarted
